"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.file_devrpc_dev = exports.ImportGraphResponseSchema = exports.Dev = void 0;
var _codegenv = require("@bufbuild/protobuf/codegenv1");
var _lightning_pb = require("../lightning_pb.js");
// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file devrpc/dev.proto (package devrpc, syntax proto3)
/* eslint-disable */

/**
 * Describes the file devrpc/dev.proto.
 */
const file_devrpc_dev = exports.file_devrpc_dev = /*@__PURE__*/
(0, _codegenv.fileDesc)("ChBkZXZycGMvZGV2LnByb3RvEgZkZXZycGMiFQoTSW1wb3J0R3JhcGhSZXNwb25zZTJGCgNEZXYSPwoLSW1wb3J0R3JhcGgSEy5sbnJwYy5DaGFubmVsR3JhcGgaGy5kZXZycGMuSW1wb3J0R3JhcGhSZXNwb25zZUIuWixnaXRodWIuY29tL2xpZ2h0bmluZ25ldHdvcmsvbG5kL2xucnBjL2RldnJwY2IGcHJvdG8z", [_lightning_pb.file_lightning]);

/**
 * @generated from message devrpc.ImportGraphResponse
 */

/**
 * Describes the message devrpc.ImportGraphResponse.
 * Use `create(ImportGraphResponseSchema)` to create a new message.
 */
const ImportGraphResponseSchema = exports.ImportGraphResponseSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_devrpc_dev, 0);

/**
 * @generated from service devrpc.Dev
 */
const Dev = exports.Dev = /*@__PURE__*/
(0, _codegenv.serviceDesc)(file_devrpc_dev, 0);
//# sourceMappingURL=dev_pb.js.map