"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.file_verrpc_verrpc = exports.Versioner = exports.VersionSchema = exports.VersionRequestSchema = void 0;
var _codegenv = require("@bufbuild/protobuf/codegenv1");
// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file verrpc/verrpc.proto (package verrpc, syntax proto3)
/* eslint-disable */

/**
 * Describes the file verrpc/verrpc.proto.
 */
const file_verrpc_verrpc = exports.file_verrpc_verrpc = /*@__PURE__*/
(0, _codegenv.fileDesc)("ChN2ZXJycGMvdmVycnBjLnByb3RvEgZ2ZXJycGMiEAoOVmVyc2lvblJlcXVlc3QiuQEKB1ZlcnNpb24SDgoGY29tbWl0GAEgASgJEhMKC2NvbW1pdF9oYXNoGAIgASgJEg8KB3ZlcnNpb24YAyABKAkSEQoJYXBwX21ham9yGAQgASgNEhEKCWFwcF9taW5vchgFIAEoDRIRCglhcHBfcGF0Y2gYBiABKA0SFwoPYXBwX3ByZV9yZWxlYXNlGAcgASgJEhIKCmJ1aWxkX3RhZ3MYCCADKAkSEgoKZ29fdmVyc2lvbhgJIAEoCTJCCglWZXJzaW9uZXISNQoKR2V0VmVyc2lvbhIWLnZlcnJwYy5WZXJzaW9uUmVxdWVzdBoPLnZlcnJwYy5WZXJzaW9uQi5aLGdpdGh1Yi5jb20vbGlnaHRuaW5nbmV0d29yay9sbmQvbG5ycGMvdmVycnBjYgZwcm90bzM");

/**
 * @generated from message verrpc.VersionRequest
 */

/**
 * Describes the message verrpc.VersionRequest.
 * Use `create(VersionRequestSchema)` to create a new message.
 */
const VersionRequestSchema = exports.VersionRequestSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_verrpc_verrpc, 0);

/**
 * @generated from message verrpc.Version
 */

/**
 * Describes the message verrpc.Version.
 * Use `create(VersionSchema)` to create a new message.
 */
const VersionSchema = exports.VersionSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_verrpc_verrpc, 1);

/**
 * Versioner is a service that can be used to get information about the version
 * and build information of the running daemon.
 *
 * @generated from service verrpc.Versioner
 */
const Versioner = exports.Versioner = /*@__PURE__*/
(0, _codegenv.serviceDesc)(file_verrpc_verrpc, 0);
//# sourceMappingURL=verrpc_pb.js.map