"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.file_watchtowerrpc_watchtower = exports.Watchtower = exports.GetInfoResponseSchema = exports.GetInfoRequestSchema = void 0;
var _codegenv = require("@bufbuild/protobuf/codegenv1");
// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file watchtowerrpc/watchtower.proto (package watchtowerrpc, syntax proto3)
/* eslint-disable */

/**
 * Describes the file watchtowerrpc/watchtower.proto.
 */
const file_watchtowerrpc_watchtower = exports.file_watchtowerrpc_watchtower = /*@__PURE__*/
(0, _codegenv.fileDesc)("Ch53YXRjaHRvd2VycnBjL3dhdGNodG93ZXIucHJvdG8SDXdhdGNodG93ZXJycGMiEAoOR2V0SW5mb1JlcXVlc3QiQgoPR2V0SW5mb1Jlc3BvbnNlEg4KBnB1YmtleRgBIAEoDBIRCglsaXN0ZW5lcnMYAiADKAkSDAoEdXJpcxgDIAMoCTJWCgpXYXRjaHRvd2VyEkgKB0dldEluZm8SHS53YXRjaHRvd2VycnBjLkdldEluZm9SZXF1ZXN0Gh4ud2F0Y2h0b3dlcnJwYy5HZXRJbmZvUmVzcG9uc2VCNVozZ2l0aHViLmNvbS9saWdodG5pbmduZXR3b3JrL2xuZC9sbnJwYy93YXRjaHRvd2VycnBjYgZwcm90bzM");

/**
 * @generated from message watchtowerrpc.GetInfoRequest
 */

/**
 * Describes the message watchtowerrpc.GetInfoRequest.
 * Use `create(GetInfoRequestSchema)` to create a new message.
 */
const GetInfoRequestSchema = exports.GetInfoRequestSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_watchtowerrpc_watchtower, 0);

/**
 * @generated from message watchtowerrpc.GetInfoResponse
 */

/**
 * Describes the message watchtowerrpc.GetInfoResponse.
 * Use `create(GetInfoResponseSchema)` to create a new message.
 */
const GetInfoResponseSchema = exports.GetInfoResponseSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_watchtowerrpc_watchtower, 1);

/**
 * Watchtower is a service that grants access to the watchtower server
 * functionality of the daemon.
 *
 * @generated from service watchtowerrpc.Watchtower
 */
const Watchtower = exports.Watchtower = /*@__PURE__*/
(0, _codegenv.serviceDesc)(file_watchtowerrpc_watchtower, 0);
//# sourceMappingURL=watchtower_pb.js.map