"use strict";

// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file verrpc/verrpc.proto (package verrpc, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
/**
 * Describes the file verrpc/verrpc.proto.
 */
export const file_verrpc_verrpc = /*@__PURE__*/
fileDesc("ChN2ZXJycGMvdmVycnBjLnByb3RvEgZ2ZXJycGMiEAoOVmVyc2lvblJlcXVlc3QiuQEKB1ZlcnNpb24SDgoGY29tbWl0GAEgASgJEhMKC2NvbW1pdF9oYXNoGAIgASgJEg8KB3ZlcnNpb24YAyABKAkSEQoJYXBwX21ham9yGAQgASgNEhEKCWFwcF9taW5vchgFIAEoDRIRCglhcHBfcGF0Y2gYBiABKA0SFwoPYXBwX3ByZV9yZWxlYXNlGAcgASgJEhIKCmJ1aWxkX3RhZ3MYCCADKAkSEgoKZ29fdmVyc2lvbhgJIAEoCTJCCglWZXJzaW9uZXISNQoKR2V0VmVyc2lvbhIWLnZlcnJwYy5WZXJzaW9uUmVxdWVzdBoPLnZlcnJwYy5WZXJzaW9uQi5aLGdpdGh1Yi5jb20vbGlnaHRuaW5nbmV0d29yay9sbmQvbG5ycGMvdmVycnBjYgZwcm90bzM");

/**
 * @generated from message verrpc.VersionRequest
 */

/**
 * Describes the message verrpc.VersionRequest.
 * Use `create(VersionRequestSchema)` to create a new message.
 */
export const VersionRequestSchema = /*@__PURE__*/
messageDesc(file_verrpc_verrpc, 0);

/**
 * @generated from message verrpc.Version
 */

/**
 * Describes the message verrpc.Version.
 * Use `create(VersionSchema)` to create a new message.
 */
export const VersionSchema = /*@__PURE__*/
messageDesc(file_verrpc_verrpc, 1);

/**
 * Versioner is a service that can be used to get information about the version
 * and build information of the running daemon.
 *
 * @generated from service verrpc.Versioner
 */
export const Versioner = /*@__PURE__*/
serviceDesc(file_verrpc_verrpc, 0);
//# sourceMappingURL=verrpc_pb.js.map