"use strict";

// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file autopilotrpc/autopilot.proto (package autopilotrpc, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
/**
 * Describes the file autopilotrpc/autopilot.proto.
 */
export const file_autopilotrpc_autopilot = /*@__PURE__*/
fileDesc("ChxhdXRvcGlsb3RycGMvYXV0b3BpbG90LnByb3RvEgxhdXRvcGlsb3RycGMiDwoNU3RhdHVzUmVxdWVzdCIgCg5TdGF0dXNSZXNwb25zZRIOCgZhY3RpdmUYASABKAgiJQoTTW9kaWZ5U3RhdHVzUmVxdWVzdBIOCgZlbmFibGUYASABKAgiFgoUTW9kaWZ5U3RhdHVzUmVzcG9uc2UiQQoSUXVlcnlTY29yZXNSZXF1ZXN0Eg8KB3B1YmtleXMYASADKAkSGgoSaWdub3JlX2xvY2FsX3N0YXRlGAIgASgIIv4BChNRdWVyeVNjb3Jlc1Jlc3BvbnNlEkIKB3Jlc3VsdHMYASADKAsyMS5hdXRvcGlsb3RycGMuUXVlcnlTY29yZXNSZXNwb25zZS5IZXVyaXN0aWNSZXN1bHQaogEKD0hldXJpc3RpY1Jlc3VsdBIRCgloZXVyaXN0aWMYASABKAkSTQoGc2NvcmVzGAIgAygLMj0uYXV0b3BpbG90cnBjLlF1ZXJ5U2NvcmVzUmVzcG9uc2UuSGV1cmlzdGljUmVzdWx0LlNjb3Jlc0VudHJ5Gi0KC1Njb3Jlc0VudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoAToCOAEikAEKEFNldFNjb3Jlc1JlcXVlc3QSEQoJaGV1cmlzdGljGAEgASgJEjoKBnNjb3JlcxgCIAMoCzIqLmF1dG9waWxvdHJwYy5TZXRTY29yZXNSZXF1ZXN0LlNjb3Jlc0VudHJ5Gi0KC1Njb3Jlc0VudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoAToCOAEiEwoRU2V0U2NvcmVzUmVzcG9uc2UyyQIKCUF1dG9waWxvdBJDCgZTdGF0dXMSGy5hdXRvcGlsb3RycGMuU3RhdHVzUmVxdWVzdBocLmF1dG9waWxvdHJwYy5TdGF0dXNSZXNwb25zZRJVCgxNb2RpZnlTdGF0dXMSIS5hdXRvcGlsb3RycGMuTW9kaWZ5U3RhdHVzUmVxdWVzdBoiLmF1dG9waWxvdHJwYy5Nb2RpZnlTdGF0dXNSZXNwb25zZRJSCgtRdWVyeVNjb3JlcxIgLmF1dG9waWxvdHJwYy5RdWVyeVNjb3Jlc1JlcXVlc3QaIS5hdXRvcGlsb3RycGMuUXVlcnlTY29yZXNSZXNwb25zZRJMCglTZXRTY29yZXMSHi5hdXRvcGlsb3RycGMuU2V0U2NvcmVzUmVxdWVzdBofLmF1dG9waWxvdHJwYy5TZXRTY29yZXNSZXNwb25zZUI0WjJnaXRodWIuY29tL2xpZ2h0bmluZ25ldHdvcmsvbG5kL2xucnBjL2F1dG9waWxvdHJwY2IGcHJvdG8z");

/**
 * @generated from message autopilotrpc.StatusRequest
 */

/**
 * Describes the message autopilotrpc.StatusRequest.
 * Use `create(StatusRequestSchema)` to create a new message.
 */
export const StatusRequestSchema = /*@__PURE__*/
messageDesc(file_autopilotrpc_autopilot, 0);

/**
 * @generated from message autopilotrpc.StatusResponse
 */

/**
 * Describes the message autopilotrpc.StatusResponse.
 * Use `create(StatusResponseSchema)` to create a new message.
 */
export const StatusResponseSchema = /*@__PURE__*/
messageDesc(file_autopilotrpc_autopilot, 1);

/**
 * @generated from message autopilotrpc.ModifyStatusRequest
 */

/**
 * Describes the message autopilotrpc.ModifyStatusRequest.
 * Use `create(ModifyStatusRequestSchema)` to create a new message.
 */
export const ModifyStatusRequestSchema = /*@__PURE__*/
messageDesc(file_autopilotrpc_autopilot, 2);

/**
 * @generated from message autopilotrpc.ModifyStatusResponse
 */

/**
 * Describes the message autopilotrpc.ModifyStatusResponse.
 * Use `create(ModifyStatusResponseSchema)` to create a new message.
 */
export const ModifyStatusResponseSchema = /*@__PURE__*/
messageDesc(file_autopilotrpc_autopilot, 3);

/**
 * @generated from message autopilotrpc.QueryScoresRequest
 */

/**
 * Describes the message autopilotrpc.QueryScoresRequest.
 * Use `create(QueryScoresRequestSchema)` to create a new message.
 */
export const QueryScoresRequestSchema = /*@__PURE__*/
messageDesc(file_autopilotrpc_autopilot, 4);

/**
 * @generated from message autopilotrpc.QueryScoresResponse
 */

/**
 * Describes the message autopilotrpc.QueryScoresResponse.
 * Use `create(QueryScoresResponseSchema)` to create a new message.
 */
export const QueryScoresResponseSchema = /*@__PURE__*/
messageDesc(file_autopilotrpc_autopilot, 5);

/**
 * @generated from message autopilotrpc.QueryScoresResponse.HeuristicResult
 */

/**
 * Describes the message autopilotrpc.QueryScoresResponse.HeuristicResult.
 * Use `create(QueryScoresResponse_HeuristicResultSchema)` to create a new message.
 */
export const QueryScoresResponse_HeuristicResultSchema = /*@__PURE__*/
messageDesc(file_autopilotrpc_autopilot, 5, 0);

/**
 * @generated from message autopilotrpc.SetScoresRequest
 */

/**
 * Describes the message autopilotrpc.SetScoresRequest.
 * Use `create(SetScoresRequestSchema)` to create a new message.
 */
export const SetScoresRequestSchema = /*@__PURE__*/
messageDesc(file_autopilotrpc_autopilot, 6);

/**
 * @generated from message autopilotrpc.SetScoresResponse
 */

/**
 * Describes the message autopilotrpc.SetScoresResponse.
 * Use `create(SetScoresResponseSchema)` to create a new message.
 */
export const SetScoresResponseSchema = /*@__PURE__*/
messageDesc(file_autopilotrpc_autopilot, 7);

/**
 * Autopilot is a service that can be used to get information about the current
 * state of the daemon's autopilot agent, and also supply it with information
 * that can be used when deciding where to open channels.
 *
 * @generated from service autopilotrpc.Autopilot
 */
export const Autopilot = /*@__PURE__*/
serviceDesc(file_autopilotrpc_autopilot, 0);
//# sourceMappingURL=autopilot_pb.js.map