// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file devrpc/dev.proto (package devrpc, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { ChannelGraphSchema } from "../lightning_pb";
import { file_lightning } from "../lightning_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file devrpc/dev.proto.
 */
export const file_devrpc_dev: GenFile = /*@__PURE__*/
  fileDesc("ChBkZXZycGMvZGV2LnByb3RvEgZkZXZycGMiFQoTSW1wb3J0R3JhcGhSZXNwb25zZTJGCgNEZXYSPwoLSW1wb3J0R3JhcGgSEy5sbnJwYy5DaGFubmVsR3JhcGgaGy5kZXZycGMuSW1wb3J0R3JhcGhSZXNwb25zZUIuWixnaXRodWIuY29tL2xpZ2h0bmluZ25ldHdvcmsvbG5kL2xucnBjL2RldnJwY2IGcHJvdG8z", [file_lightning]);

/**
 * @generated from message devrpc.ImportGraphResponse
 */
export type ImportGraphResponse = Message<"devrpc.ImportGraphResponse"> & {
};

/**
 * Describes the message devrpc.ImportGraphResponse.
 * Use `create(ImportGraphResponseSchema)` to create a new message.
 */
export const ImportGraphResponseSchema: GenMessage<ImportGraphResponse> = /*@__PURE__*/
  messageDesc(file_devrpc_dev, 0);

/**
 * @generated from service devrpc.Dev
 */
export const Dev: GenService<{
  /**
   * 
   * ImportGraph imports a ChannelGraph into the graph database. Should only be
   * used for development.
   *
   * @generated from rpc devrpc.Dev.ImportGraph
   */
  importGraph: {
    methodKind: "unary";
    input: typeof ChannelGraphSchema;
    output: typeof ImportGraphResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_devrpc_dev, 0);

