"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;
var _reactNative = require("react-native");
// Note to react-native-turbo-lnd contributors:
// This file is automatically generated by the protoc plugin inside the
// protoc-generator folder.
// Any changes to this file should be made there instead.
/* eslint-disable */
// Protobufs will be encoded as base64 strings.
// Use a protobuf utility like protobufjs or protobuf-es to encode/decode them.
// Bidi streams will return this interface for where can send data to the
// stream.
// Read streams will call OnResponseCallback when data is available.
// UnsubscribeFromStream can be used to stop the stream.
var _default = exports.default = _reactNative.TurboModuleRegistry.getEnforcing("TurboLndModuleCxx");
//# sourceMappingURL=NativeTurboLnd.js.map