"use strict";

// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file devrpc/dev.proto (package devrpc, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_lightning } from "../lightning_pb.js";
/**
 * Describes the file devrpc/dev.proto.
 */
export const file_devrpc_dev = /*@__PURE__*/
fileDesc("ChBkZXZycGMvZGV2LnByb3RvEgZkZXZycGMiFQoTSW1wb3J0R3JhcGhSZXNwb25zZTJGCgNEZXYSPwoLSW1wb3J0R3JhcGgSEy5sbnJwYy5DaGFubmVsR3JhcGgaGy5kZXZycGMuSW1wb3J0R3JhcGhSZXNwb25zZUIuWixnaXRodWIuY29tL2xpZ2h0bmluZ25ldHdvcmsvbG5kL2xucnBjL2RldnJwY2IGcHJvdG8z", [file_lightning]);

/**
 * @generated from message devrpc.ImportGraphResponse
 */

/**
 * Describes the message devrpc.ImportGraphResponse.
 * Use `create(ImportGraphResponseSchema)` to create a new message.
 */
export const ImportGraphResponseSchema = /*@__PURE__*/
messageDesc(file_devrpc_dev, 0);

/**
 * @generated from service devrpc.Dev
 */
export const Dev = /*@__PURE__*/
serviceDesc(file_devrpc_dev, 0);
//# sourceMappingURL=dev_pb.js.map