"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.file_invoicesrpc_invoices = exports.SubscribeSingleInvoiceRequestSchema = exports.SettleInvoiceRespSchema = exports.SettleInvoiceMsgSchema = exports.LookupModifierSchema = exports.LookupModifier = exports.LookupInvoiceMsgSchema = exports.Invoices = exports.CancelInvoiceRespSchema = exports.CancelInvoiceMsgSchema = exports.AddHoldInvoiceRespSchema = exports.AddHoldInvoiceRequestSchema = void 0;
var _codegenv = require("@bufbuild/protobuf/codegenv1");
var _lightning_pb = require("../lightning_pb.js");
// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file invoicesrpc/invoices.proto (package invoicesrpc, syntax proto3)
/* eslint-disable */

/**
 * Describes the file invoicesrpc/invoices.proto.
 */
const file_invoicesrpc_invoices = exports.file_invoicesrpc_invoices = /*@__PURE__*/
(0, _codegenv.fileDesc)("ChppbnZvaWNlc3JwYy9pbnZvaWNlcy5wcm90bxILaW52b2ljZXNycGMiKAoQQ2FuY2VsSW52b2ljZU1zZxIUCgxwYXltZW50X2hhc2gYASABKAwiEwoRQ2FuY2VsSW52b2ljZVJlc3Ai5AEKFUFkZEhvbGRJbnZvaWNlUmVxdWVzdBIMCgRtZW1vGAEgASgJEgwKBGhhc2gYAiABKAwSDQoFdmFsdWUYAyABKAMSEgoKdmFsdWVfbXNhdBgKIAEoAxIYChBkZXNjcmlwdGlvbl9oYXNoGAQgASgMEg4KBmV4cGlyeRgFIAEoAxIVCg1mYWxsYmFja19hZGRyGAYgASgJEhMKC2NsdHZfZXhwaXJ5GAcgASgEEiUKC3JvdXRlX2hpbnRzGAggAygLMhAubG5ycGMuUm91dGVIaW50Eg8KB3ByaXZhdGUYCSABKAgiVgoSQWRkSG9sZEludm9pY2VSZXNwEhcKD3BheW1lbnRfcmVxdWVzdBgBIAEoCRIRCglhZGRfaW5kZXgYAiABKAQSFAoMcGF5bWVudF9hZGRyGAMgASgMIiQKEFNldHRsZUludm9pY2VNc2cSEAoIcHJlaW1hZ2UYASABKAwiEwoRU2V0dGxlSW52b2ljZVJlc3AiNQodU3Vic2NyaWJlU2luZ2xlSW52b2ljZVJlcXVlc3QSDgoGcl9oYXNoGAIgASgMSgQIARACIpkBChBMb29rdXBJbnZvaWNlTXNnEhYKDHBheW1lbnRfaGFzaBgBIAEoDEgAEhYKDHBheW1lbnRfYWRkchgCIAEoDEgAEhAKBnNldF9pZBgDIAEoDEgAEjQKD2xvb2t1cF9tb2RpZmllchgEIAEoDjIbLmludm9pY2VzcnBjLkxvb2t1cE1vZGlmaWVyQg0KC2ludm9pY2VfcmVmKkQKDkxvb2t1cE1vZGlmaWVyEgsKB0RFRkFVTFQQABIRCg1IVExDX1NFVF9PTkxZEAESEgoOSFRMQ19TRVRfQkxBTksQAjKbAwoISW52b2ljZXMSVgoWU3Vic2NyaWJlU2luZ2xlSW52b2ljZRIqLmludm9pY2VzcnBjLlN1YnNjcmliZVNpbmdsZUludm9pY2VSZXF1ZXN0Gg4ubG5ycGMuSW52b2ljZTABEk4KDUNhbmNlbEludm9pY2USHS5pbnZvaWNlc3JwYy5DYW5jZWxJbnZvaWNlTXNnGh4uaW52b2ljZXNycGMuQ2FuY2VsSW52b2ljZVJlc3ASVQoOQWRkSG9sZEludm9pY2USIi5pbnZvaWNlc3JwYy5BZGRIb2xkSW52b2ljZVJlcXVlc3QaHy5pbnZvaWNlc3JwYy5BZGRIb2xkSW52b2ljZVJlc3ASTgoNU2V0dGxlSW52b2ljZRIdLmludm9pY2VzcnBjLlNldHRsZUludm9pY2VNc2caHi5pbnZvaWNlc3JwYy5TZXR0bGVJbnZvaWNlUmVzcBJACg9Mb29rdXBJbnZvaWNlVjISHS5pbnZvaWNlc3JwYy5Mb29rdXBJbnZvaWNlTXNnGg4ubG5ycGMuSW52b2ljZUIzWjFnaXRodWIuY29tL2xpZ2h0bmluZ25ldHdvcmsvbG5kL2xucnBjL2ludm9pY2VzcnBjYgZwcm90bzM", [_lightning_pb.file_lightning]);

/**
 * @generated from message invoicesrpc.CancelInvoiceMsg
 */

/**
 * Describes the message invoicesrpc.CancelInvoiceMsg.
 * Use `create(CancelInvoiceMsgSchema)` to create a new message.
 */
const CancelInvoiceMsgSchema = exports.CancelInvoiceMsgSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_invoicesrpc_invoices, 0);

/**
 * @generated from message invoicesrpc.CancelInvoiceResp
 */

/**
 * Describes the message invoicesrpc.CancelInvoiceResp.
 * Use `create(CancelInvoiceRespSchema)` to create a new message.
 */
const CancelInvoiceRespSchema = exports.CancelInvoiceRespSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_invoicesrpc_invoices, 1);

/**
 * @generated from message invoicesrpc.AddHoldInvoiceRequest
 */

/**
 * Describes the message invoicesrpc.AddHoldInvoiceRequest.
 * Use `create(AddHoldInvoiceRequestSchema)` to create a new message.
 */
const AddHoldInvoiceRequestSchema = exports.AddHoldInvoiceRequestSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_invoicesrpc_invoices, 2);

/**
 * @generated from message invoicesrpc.AddHoldInvoiceResp
 */

/**
 * Describes the message invoicesrpc.AddHoldInvoiceResp.
 * Use `create(AddHoldInvoiceRespSchema)` to create a new message.
 */
const AddHoldInvoiceRespSchema = exports.AddHoldInvoiceRespSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_invoicesrpc_invoices, 3);

/**
 * @generated from message invoicesrpc.SettleInvoiceMsg
 */

/**
 * Describes the message invoicesrpc.SettleInvoiceMsg.
 * Use `create(SettleInvoiceMsgSchema)` to create a new message.
 */
const SettleInvoiceMsgSchema = exports.SettleInvoiceMsgSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_invoicesrpc_invoices, 4);

/**
 * @generated from message invoicesrpc.SettleInvoiceResp
 */

/**
 * Describes the message invoicesrpc.SettleInvoiceResp.
 * Use `create(SettleInvoiceRespSchema)` to create a new message.
 */
const SettleInvoiceRespSchema = exports.SettleInvoiceRespSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_invoicesrpc_invoices, 5);

/**
 * @generated from message invoicesrpc.SubscribeSingleInvoiceRequest
 */

/**
 * Describes the message invoicesrpc.SubscribeSingleInvoiceRequest.
 * Use `create(SubscribeSingleInvoiceRequestSchema)` to create a new message.
 */
const SubscribeSingleInvoiceRequestSchema = exports.SubscribeSingleInvoiceRequestSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_invoicesrpc_invoices, 6);

/**
 * @generated from message invoicesrpc.LookupInvoiceMsg
 */

/**
 * Describes the message invoicesrpc.LookupInvoiceMsg.
 * Use `create(LookupInvoiceMsgSchema)` to create a new message.
 */
const LookupInvoiceMsgSchema = exports.LookupInvoiceMsgSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_invoicesrpc_invoices, 7);

/**
 * @generated from enum invoicesrpc.LookupModifier
 */
let LookupModifier = exports.LookupModifier = /*#__PURE__*/function (LookupModifier) {
  LookupModifier[LookupModifier["DEFAULT"] = 0] = "DEFAULT";
  LookupModifier[LookupModifier["HTLC_SET_ONLY"] = 1] = "HTLC_SET_ONLY";
  LookupModifier[LookupModifier["HTLC_SET_BLANK"] = 2] = "HTLC_SET_BLANK";
  return LookupModifier;
}({});
/**
 * Describes the enum invoicesrpc.LookupModifier.
 */
const LookupModifierSchema = exports.LookupModifierSchema = /*@__PURE__*/
(0, _codegenv.enumDesc)(file_invoicesrpc_invoices, 0);

/**
 * Invoices is a service that can be used to create, accept, settle and cancel
 * invoices.
 *
 * @generated from service invoicesrpc.Invoices
 */
const Invoices = exports.Invoices = /*@__PURE__*/
(0, _codegenv.serviceDesc)(file_invoicesrpc_invoices, 0);
//# sourceMappingURL=invoices_pb.js.map