// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file verrpc/verrpc.proto (package verrpc, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file verrpc/verrpc.proto.
 */
export const file_verrpc_verrpc: GenFile = /*@__PURE__*/
  fileDesc("ChN2ZXJycGMvdmVycnBjLnByb3RvEgZ2ZXJycGMiEAoOVmVyc2lvblJlcXVlc3QiuQEKB1ZlcnNpb24SDgoGY29tbWl0GAEgASgJEhMKC2NvbW1pdF9oYXNoGAIgASgJEg8KB3ZlcnNpb24YAyABKAkSEQoJYXBwX21ham9yGAQgASgNEhEKCWFwcF9taW5vchgFIAEoDRIRCglhcHBfcGF0Y2gYBiABKA0SFwoPYXBwX3ByZV9yZWxlYXNlGAcgASgJEhIKCmJ1aWxkX3RhZ3MYCCADKAkSEgoKZ29fdmVyc2lvbhgJIAEoCTJCCglWZXJzaW9uZXISNQoKR2V0VmVyc2lvbhIWLnZlcnJwYy5WZXJzaW9uUmVxdWVzdBoPLnZlcnJwYy5WZXJzaW9uQi5aLGdpdGh1Yi5jb20vbGlnaHRuaW5nbmV0d29yay9sbmQvbG5ycGMvdmVycnBjYgZwcm90bzM");

/**
 * @generated from message verrpc.VersionRequest
 */
export type VersionRequest = Message<"verrpc.VersionRequest"> & {
};

/**
 * Describes the message verrpc.VersionRequest.
 * Use `create(VersionRequestSchema)` to create a new message.
 */
export const VersionRequestSchema: GenMessage<VersionRequest> = /*@__PURE__*/
  messageDesc(file_verrpc_verrpc, 0);

/**
 * @generated from message verrpc.Version
 */
export type Version = Message<"verrpc.Version"> & {
  /**
   * A verbose description of the daemon's commit.
   *
   * @generated from field: string commit = 1;
   */
  commit: string;

  /**
   * The SHA1 commit hash that the daemon is compiled with.
   *
   * @generated from field: string commit_hash = 2;
   */
  commitHash: string;

  /**
   * The semantic version.
   *
   * @generated from field: string version = 3;
   */
  version: string;

  /**
   * The major application version.
   *
   * @generated from field: uint32 app_major = 4;
   */
  appMajor: number;

  /**
   * The minor application version.
   *
   * @generated from field: uint32 app_minor = 5;
   */
  appMinor: number;

  /**
   * The application patch number.
   *
   * @generated from field: uint32 app_patch = 6;
   */
  appPatch: number;

  /**
   * The application pre-release modifier, possibly empty.
   *
   * @generated from field: string app_pre_release = 7;
   */
  appPreRelease: string;

  /**
   * The list of build tags that were supplied during compilation.
   *
   * @generated from field: repeated string build_tags = 8;
   */
  buildTags: string[];

  /**
   * The version of go that compiled the executable.
   *
   * @generated from field: string go_version = 9;
   */
  goVersion: string;
};

/**
 * Describes the message verrpc.Version.
 * Use `create(VersionSchema)` to create a new message.
 */
export const VersionSchema: GenMessage<Version> = /*@__PURE__*/
  messageDesc(file_verrpc_verrpc, 1);

/**
 * Versioner is a service that can be used to get information about the version
 * and build information of the running daemon.
 *
 * @generated from service verrpc.Versioner
 */
export const Versioner: GenService<{
  /**
   * lncli: `version`
   * GetVersion returns the current version and build information of the running
   * daemon.
   *
   * @generated from rpc verrpc.Versioner.GetVersion
   */
  getVersion: {
    methodKind: "unary";
    input: typeof VersionRequestSchema;
    output: typeof VersionSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_verrpc_verrpc, 0);

