"use strict";

// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file chainrpc/chainnotifier.proto (package chainrpc, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
/**
 * Describes the file chainrpc/chainnotifier.proto.
 */
export const file_chainrpc_chainnotifier = /*@__PURE__*/
fileDesc("ChxjaGFpbnJwYy9jaGFpbm5vdGlmaWVyLnByb3RvEghjaGFpbnJwYyJqCgtDb25mUmVxdWVzdBIMCgR0eGlkGAEgASgMEg4KBnNjcmlwdBgCIAEoDBIRCgludW1fY29uZnMYAyABKA0SEwoLaGVpZ2h0X2hpbnQYBCABKA0SFQoNaW5jbHVkZV9ibG9jaxgFIAEoCCJsCgtDb25mRGV0YWlscxIOCgZyYXdfdHgYASABKAwSEgoKYmxvY2tfaGFzaBgCIAEoDBIUCgxibG9ja19oZWlnaHQYAyABKA0SEAoIdHhfaW5kZXgYBCABKA0SEQoJcmF3X2Jsb2NrGAUgASgMIgcKBVJlb3JnIl0KCUNvbmZFdmVudBIlCgRjb25mGAEgASgLMhUuY2hhaW5ycGMuQ29uZkRldGFpbHNIABIgCgVyZW9yZxgCIAEoCzIPLmNoYWlucnBjLlJlb3JnSABCBwoFZXZlbnQiJwoIT3V0cG9pbnQSDAoEaGFzaBgBIAEoDBINCgVpbmRleBgCIAEoDSJZCgxTcGVuZFJlcXVlc3QSJAoIb3V0cG9pbnQYASABKAsyEi5jaGFpbnJwYy5PdXRwb2ludBIOCgZzY3JpcHQYAiABKAwSEwoLaGVpZ2h0X2hpbnQYAyABKA0ipwEKDFNwZW5kRGV0YWlscxItChFzcGVuZGluZ19vdXRwb2ludBgBIAEoCzISLmNoYWlucnBjLk91dHBvaW50EhcKD3Jhd19zcGVuZGluZ190eBgCIAEoDBIYChBzcGVuZGluZ190eF9oYXNoGAMgASgMEhwKFHNwZW5kaW5nX2lucHV0X2luZGV4GAQgASgNEhcKD3NwZW5kaW5nX2hlaWdodBgFIAEoDSJgCgpTcGVuZEV2ZW50EicKBXNwZW5kGAEgASgLMhYuY2hhaW5ycGMuU3BlbmREZXRhaWxzSAASIAoFcmVvcmcYAiABKAsyDy5jaGFpbnJwYy5SZW9yZ0gAQgcKBWV2ZW50IioKCkJsb2NrRXBvY2gSDAoEaGFzaBgBIAEoDBIOCgZoZWlnaHQYAiABKA0y5wEKDUNoYWluTm90aWZpZXISSQoZUmVnaXN0ZXJDb25maXJtYXRpb25zTnRmbhIVLmNoYWlucnBjLkNvbmZSZXF1ZXN0GhMuY2hhaW5ycGMuQ29uZkV2ZW50MAESQwoRUmVnaXN0ZXJTcGVuZE50Zm4SFi5jaGFpbnJwYy5TcGVuZFJlcXVlc3QaFC5jaGFpbnJwYy5TcGVuZEV2ZW50MAESRgoWUmVnaXN0ZXJCbG9ja0Vwb2NoTnRmbhIULmNoYWlucnBjLkJsb2NrRXBvY2gaFC5jaGFpbnJwYy5CbG9ja0Vwb2NoMAFCMFouZ2l0aHViLmNvbS9saWdodG5pbmduZXR3b3JrL2xuZC9sbnJwYy9jaGFpbnJwY2IGcHJvdG8z");

/**
 * @generated from message chainrpc.ConfRequest
 */

/**
 * Describes the message chainrpc.ConfRequest.
 * Use `create(ConfRequestSchema)` to create a new message.
 */
export const ConfRequestSchema = /*@__PURE__*/
messageDesc(file_chainrpc_chainnotifier, 0);

/**
 * @generated from message chainrpc.ConfDetails
 */

/**
 * Describes the message chainrpc.ConfDetails.
 * Use `create(ConfDetailsSchema)` to create a new message.
 */
export const ConfDetailsSchema = /*@__PURE__*/
messageDesc(file_chainrpc_chainnotifier, 1);

/**
 * TODO(wilmer): need to know how the client will use this first.
 *
 * @generated from message chainrpc.Reorg
 */

/**
 * Describes the message chainrpc.Reorg.
 * Use `create(ReorgSchema)` to create a new message.
 */
export const ReorgSchema = /*@__PURE__*/
messageDesc(file_chainrpc_chainnotifier, 2);

/**
 * @generated from message chainrpc.ConfEvent
 */

/**
 * Describes the message chainrpc.ConfEvent.
 * Use `create(ConfEventSchema)` to create a new message.
 */
export const ConfEventSchema = /*@__PURE__*/
messageDesc(file_chainrpc_chainnotifier, 3);

/**
 * @generated from message chainrpc.Outpoint
 */

/**
 * Describes the message chainrpc.Outpoint.
 * Use `create(OutpointSchema)` to create a new message.
 */
export const OutpointSchema = /*@__PURE__*/
messageDesc(file_chainrpc_chainnotifier, 4);

/**
 * @generated from message chainrpc.SpendRequest
 */

/**
 * Describes the message chainrpc.SpendRequest.
 * Use `create(SpendRequestSchema)` to create a new message.
 */
export const SpendRequestSchema = /*@__PURE__*/
messageDesc(file_chainrpc_chainnotifier, 5);

/**
 * @generated from message chainrpc.SpendDetails
 */

/**
 * Describes the message chainrpc.SpendDetails.
 * Use `create(SpendDetailsSchema)` to create a new message.
 */
export const SpendDetailsSchema = /*@__PURE__*/
messageDesc(file_chainrpc_chainnotifier, 6);

/**
 * @generated from message chainrpc.SpendEvent
 */

/**
 * Describes the message chainrpc.SpendEvent.
 * Use `create(SpendEventSchema)` to create a new message.
 */
export const SpendEventSchema = /*@__PURE__*/
messageDesc(file_chainrpc_chainnotifier, 7);

/**
 * @generated from message chainrpc.BlockEpoch
 */

/**
 * Describes the message chainrpc.BlockEpoch.
 * Use `create(BlockEpochSchema)` to create a new message.
 */
export const BlockEpochSchema = /*@__PURE__*/
messageDesc(file_chainrpc_chainnotifier, 8);

/**
 * ChainNotifier is a service that can be used to get information about the
 * chain backend by registering notifiers for chain events.
 *
 * @generated from service chainrpc.ChainNotifier
 */
export const ChainNotifier = /*@__PURE__*/
serviceDesc(file_chainrpc_chainnotifier, 0);

// Merged from chainkit_pb.ts
export const file_chainrpc_chainkit = /*@__PURE__*/
fileDesc("ChdjaGFpbnJwYy9jaGFpbmtpdC5wcm90bxIIY2hhaW5ycGMiJQoPR2V0QmxvY2tSZXF1ZXN0EhIKCmJsb2NrX2hhc2gYASABKAwiJQoQR2V0QmxvY2tSZXNwb25zZRIRCglyYXdfYmxvY2sYASABKAwiFQoTR2V0QmVzdEJsb2NrUmVxdWVzdCJAChRHZXRCZXN0QmxvY2tSZXNwb25zZRISCgpibG9ja19oYXNoGAEgASgMEhQKDGJsb2NrX2hlaWdodBgCIAEoBSIrChNHZXRCbG9ja0hhc2hSZXF1ZXN0EhQKDGJsb2NrX2hlaWdodBgBIAEoAyIqChRHZXRCbG9ja0hhc2hSZXNwb25zZRISCgpibG9ja19oYXNoGAEgASgMMusBCghDaGFpbktpdBJBCghHZXRCbG9jaxIZLmNoYWlucnBjLkdldEJsb2NrUmVxdWVzdBoaLmNoYWlucnBjLkdldEJsb2NrUmVzcG9uc2USTQoMR2V0QmVzdEJsb2NrEh0uY2hhaW5ycGMuR2V0QmVzdEJsb2NrUmVxdWVzdBoeLmNoYWlucnBjLkdldEJlc3RCbG9ja1Jlc3BvbnNlEk0KDEdldEJsb2NrSGFzaBIdLmNoYWlucnBjLkdldEJsb2NrSGFzaFJlcXVlc3QaHi5jaGFpbnJwYy5HZXRCbG9ja0hhc2hSZXNwb25zZUIwWi5naXRodWIuY29tL2xpZ2h0bmluZ25ldHdvcmsvbG5kL2xucnBjL2NoYWlucnBjYgZwcm90bzM");

/**
 * @generated from message chainrpc.GetBlockRequest
 */

/**
 * Describes the message chainrpc.GetBlockRequest.
 * Use `create(GetBlockRequestSchema)` to create a new message.
 */
export const GetBlockRequestSchema = /*@__PURE__*/
messageDesc(file_chainrpc_chainkit, 0);

/**
 * TODO(ffranr): The neutrino GetBlock response includes many
 * additional helpful fields. Consider adding them here also.
 *
 * @generated from message chainrpc.GetBlockResponse
 */

/**
 * Describes the message chainrpc.GetBlockResponse.
 * Use `create(GetBlockResponseSchema)` to create a new message.
 */
export const GetBlockResponseSchema = /*@__PURE__*/
messageDesc(file_chainrpc_chainkit, 1);

/**
 * @generated from message chainrpc.GetBestBlockRequest
 */

/**
 * Describes the message chainrpc.GetBestBlockRequest.
 * Use `create(GetBestBlockRequestSchema)` to create a new message.
 */
export const GetBestBlockRequestSchema = /*@__PURE__*/
messageDesc(file_chainrpc_chainkit, 2);

/**
 * @generated from message chainrpc.GetBestBlockResponse
 */

/**
 * Describes the message chainrpc.GetBestBlockResponse.
 * Use `create(GetBestBlockResponseSchema)` to create a new message.
 */
export const GetBestBlockResponseSchema = /*@__PURE__*/
messageDesc(file_chainrpc_chainkit, 3);

/**
 * @generated from message chainrpc.GetBlockHashRequest
 */

/**
 * Describes the message chainrpc.GetBlockHashRequest.
 * Use `create(GetBlockHashRequestSchema)` to create a new message.
 */
export const GetBlockHashRequestSchema = /*@__PURE__*/
messageDesc(file_chainrpc_chainkit, 4);

/**
 * @generated from message chainrpc.GetBlockHashResponse
 */

/**
 * Describes the message chainrpc.GetBlockHashResponse.
 * Use `create(GetBlockHashResponseSchema)` to create a new message.
 */
export const GetBlockHashResponseSchema = /*@__PURE__*/
messageDesc(file_chainrpc_chainkit, 5);

/**
 * ChainKit is a service that can be used to get information from the
 * chain backend.
 *
 * @generated from service chainrpc.ChainKit
 */
export const ChainKit = /*@__PURE__*/
serviceDesc(file_chainrpc_chainkit, 0);
//# sourceMappingURL=chainnotifier_pb.js.map